### ISSUE TITLE
Crash due to issue with nbt-crafting

### ISSUE THREAD

**Issue by lostcoder** [AlexIIL/SimplePipes#31] opened 2020-01-20 08:35 UTC
nbt-crafting seems to be expecting more data in the buffer.

java.lang.IndexOutOfBoundsException: readerIndex(5) + length(1) exceeds writerIndex(5): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 5, widx: 5, cap: 256)
    at Not Enough Crashes deobfuscated stack trace.(1.15.1+build.37)
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405)
    at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:707)
    at net.minecraft.util.PacketByteBuf.readByte(PacketByteBuf:867)
    at net.minecraft.util.PacketByteBuf.readCompoundTag(PacketByteBuf:312)
    at de.siphalor.nbtcrafting.ingredient.IngredientEntryCondition.read(IngredientEntryCondition.java:81)
    at de.siphalor.nbtcrafting.ingredient.IngredientMultiStackEntry.read(IngredientMultiStackEntry.java:73)
    at net.minecraft.recipe.Ingredient.handler$zih000$fromPacket(Ingredient:658)
    at net.minecraft.recipe.Ingredient.fromPacket(Ingredient)
    at alexiil.mc.mod.pipes.part.SimplePipeParts.createIngredient(SimplePipeParts.java:173)
    at alexiil.mc.mod.pipes.part.SimplePipeParts.generateBlockToFacadeCuttingRecipes(SimplePipeParts.java:94)
    at alexiil.mc.mod.pipes.part.SimplePipeParts.addFacadeRecipes(SimplePipeParts.java:83)
    at net.minecraft.recipe.RecipeManager.invoke(RecipeManager:1567)
    at net.minecraft.recipe.RecipeManager.handler$zki000$getAllMatches(RecipeManager:1555)
    at net.minecraft.recipe.RecipeManager.getAllMatches(RecipeManager)
    at net.minecraft.container.StonecutterContainer.updateInput(StonecutterContainer:148)
    at net.minecraft.container.StonecutterContainer.onContentChanged(StonecutterContainer:138)
    at net.minecraft.class_3971$1.markDirty(class_3971.java:44)
    at net.minecraft.inventory.BasicInventory.setInvStack(BasicInventory:117)
    at net.minecraft.container.Slot.setStack(Slot:82)
    at net.minecraft.container.Container.onSlotClick(Container:278)

Both mods are installed as part of  All Of Fabric 2.  Single player world if it matters.

**Comment by AlexIIL** [comment] 2020-01-20 14:09
...oh. This is caused by how simple pipes' creates `Ingredient` instances: currently I hack around the `ofStacks()` method being client-side only by writing the stack to a packetbuffer and then deserialising it, however nbt-crafting changes `Ingredient` to write out more data.

I'm not quite sure how I'll fix this but I'm pretty sure it's on SP to fix this, not nbt-crafting.

**Comment by AlexIIL** [comment] 2020-02-06 22:28
Ok, this should be fixed in 0.3.4.

**Closed as completed by AlexIIL** 2020-02-06 22:28 UTC
Labels: bug
