### ISSUE TITLE
Crash on Server, not on Single Player when placing pipe, MC 1.21 // Fabric 0.16.7

### ISSUE THREAD

**Issue by martfromit** [AlexIIL/SimplePipes#76] opened 2024-11-12 14:56 UTC
When placing a pipe, server crash.
In single player works.

Need it for TechReborn.
Installed Mods:
PipePlus-1.21-1.1.5.jar
simplepipes-all-0.13.0-pre.2.jar

I hope somebody can help me.

Server-Log:
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 2024-11-12 14:43:35
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/Lists
	at knot//alexiil.mc.mod.pipes.pipe.PipeSpFlowItem.writeToBuffer(PipeSpFlowItem.java:123)
	at knot//alexiil.mc.mod.pipes.pipe.PartSpPipe.writeToBuffer(PartSpPipe.java:137)
	at knot//alexiil.mc.mod.pipes.pipe.PartSpPipe.writeCreationData(PartSpPipe.java:143)
	at knot//alexiil.mc.lib.multipart.impl.PartHolder.writeCreation(PartHolder.java:195)
	at knot//alexiil.mc.lib.multipart.impl.PartContainer.writeInitialRenderData(PartContainer.java:824)
	at knot//alexiil.mc.lib.net.NetIdDataK.send(NetIdDataK.java:78)
	at knot//alexiil.mc.lib.net.NetIdDataK.send(NetIdDataK.java:53)
	at knot//alexiil.mc.lib.multipart.impl.MultipartBlockEntity.sendInitialData(MultipartBlockEntity.java:94)
	at knot//net.minecraft.class_8608.handler$znn000$libnetworkstack$postSendPackets(class_8608.java:530)
	at knot//net.minecraft.class_8608.method_52388(class_8608.java:94)
	at knot//net.minecraft.class_8608.method_52386(class_8608.java:81)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1045)
	at knot//net.minecraft.class_3176.method_3813(class_3176.java:299)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.Lists
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Linux (amd64) version 5.4.0-135-generic
	Java Version: 21.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 3628102856 bytes (3460 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 64
	Processor Vendor: AuthenticAMD
	Processor Name: AMD EPYC 7282 16-Core Processor
	Identifier: AuthenticAMD Family 23 Model 49 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 2
	Number of physical CPUs: 32
	Number of logical CPUs: 64
	Graphics card #0 name: MGA G200eH3
	Graphics card #0 vendor: Matrox Electronics Systems Ltd. (0x102b)
	Graphics card #0 VRAM (MiB): 16.00
	Graphics card #0 deviceId: 0x0538
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 380771.16
	Virtual memory used (MiB): 400944.75
	Swap memory total (MiB): 122880.00
	Swap memory used (MiB): 8761.75
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 1182924.00, total: 1866604.88
	Space in storage for workdir (MiB): available: 1182924.00, total: 1866604.88
	JVM Flags: 20 total; -Xms4096M -Xmx4096M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=32M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Fabric Mods: 
		architectury: Architectury 13.0.1
		collective: Collective 7.74
		connectedglass: Connected Glass 1.1.12
		enhanced_quarries: Enhanced Quarries 1.5.2
		fabric-api: Fabric API 0.102.0+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.16+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae06d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+78017270d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df360d1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209bd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+a551f7a4d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209bd1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b1d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+56599129d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b5597344d1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+176f9036d1
		fabricloader: Fabric Loader 0.16.7
			mixinextras: MixinExtras 0.4.1
		fusion: Fusion 1.1.1
		java: OpenJDK 64-Bit Server VM 21
		justhammers: Just Hammers 21.0.2
		libblockattributes: LibBlockAttributes 0.16.0-pre.2
			libblockattributes_fluids: LibBlockAttributes (Fluids) 0.16.0-pre.2
			libblockattributes_items: LibBlockAttributes (Items) 0.16.0-pre.2
		libmultipart_deps_container: LibMultiPart (Dependency Container) 0.13.0-pre.1
			libblockattributes_core: LibBlockAttributes (Core) 0.16.0-pre.2
			libmultipart: LibMultiPart 0.13.0-pre.1
			libmultipart_compat: LibMultiPart (Mod Compatibility) 0.13.0-pre.1
			libnetworkstack: Lib Network Stack 0.13.0-pre.1
		mcpitanlib: MCPitanLib 2.5.2-1.21-fabric
			cloth-config: Cloth Config v15 15.0.127
				cloth-basic-math: cloth-basic-math 0.6.1
			compatdatapacks76: CompatDatapacks 1.0.10.210-fabric
			org_yaml_snakeyaml: snakeyaml 2.0
		minecraft: Minecraft 1.21
		moonlight: Moonlight Lib 1.21-2.15.15
		oreharvester: Ore Harvester 1.3
		pipeplus: PipePlus 1.21-1.1.5
		reinfchest: Reinforced Chests 3.0.1+1.21
			reinfcore: Reinforced Core 4.0.1+1.21
		replantingcrops: Replanting Crops 5.3
		sawmill: Universal Sawmill 1.21-1.5.9
		simple_pipes_dep_container: SimplePipeTest (Dependency Container) 0.13.0-pre.2
			simple_pipes: SimplePipeTest 0.13.0-pre.2
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17+c
		techreborn: Tech Reborn 5.11.11
			reborncore: Reborn Core 5.11.11
			team_reborn_energy: Energy 4.1.0
		treeharvester: Tree Harvester 8.9
	Server Running: true
	Player Count: 1 / 4; [class_3222['Playername'/665, l='ServerLevel[NeueInsel]', x=82.24, y=63.00, z=-697.35]]
	Active Data Packs: vanilla, bundle, fabric, collective, connectedglass (incompatible), enhanced_quarries, fabric-convention-tags-v2, justhammers, moonlight, pipeplus, reinfchest, sawmill, simple_pipes, supermartijn642corelib (incompatible), techreborn, sawmill:sawmill_recipes
	Available Data Packs: bundle, collective, connectedglass (incompatible), enhanced_quarries, fabric, fabric-convention-tags-v2, justhammers, moonlight, pipeplus, reinfchest, sawmill, sawmill:sawmill_recipes, simple_pipes, supermartijn642corelib (incompatible), techreborn, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:bundle, minecraft:vanilla
	World Generation: Stable
	World Seed: -1674187430
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by Kneelawk** [comment] 2024-11-12 15:28
Duplicate of #75. I'll have a fix out shortly.

**Comment by Kneelawk** [comment] 2024-11-12 16:01
Ok, this should be fixed in version `[1.21.1] 0.13.0` now, which is available on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/simplepipes/files/5897218) and [Modrinth](https://modrinth.com/mod/simple-pipes/version/0.13.0).

**Closed as completed by Kneelawk** 2024-11-12 16:01 UTC

**Comment by martfromit** [comment] 2024-11-12 16:20
Does it work on 1.21 ? 
I see the Fix is for 1.21.1
